add fix patch, add ccache , apt-cache, add Clear_All_Workflow.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -53,6 +53,36 @@ runs:
           remove-cached-tools: 'false'   # Avoid unless confirmed safe
           verbose: 'false'                # Enable detailed logging
 
+      - name: Create and Enable 3G Swap
+        shell: bash
+        run: |
+          sudo swapoff -a
+          sudo fallocate -l 3G /swapfile
+          sudo chmod 600 /swapfile
+          sudo mkswap /swapfile
+          sudo swapon /swapfile
+          free -h
+
+      - name: 🛠 Configure APT caching (配置APT缓存)
+        shell: bash
+        run: |
+          APT_CACHE_DIR="$HOME/apt-cache"
+          mkdir -p "$APT_CACHE_DIR"/{archives,lists/partial}
+          echo "Dir::Cache \"$APT_CACHE_DIR\";" | sudo tee /etc/apt/apt.conf.d/90user-cache
+          echo "Dir::Cache::archives \"$APT_CACHE_DIR/archives\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
+          echo "Dir::State::lists \"$APT_CACHE_DIR/lists\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
+          echo "Acquire::Check-Valid-Until \"false\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
+          echo "Acquire::Languages \"none\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
+          sudo chown -R $USER:$USER "$APT_CACHE_DIR"
+
+      - name: 🛠 Cache APT packages (缓存APT包)
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.HOME }}/apt-cache
+          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/batch-build-kernel-release.yml') }}
+          restore-keys: |
+            ${{ runner.os }}-apt-
+
       - name: Setup Build System
         shell: bash
         run: |
@@ -88,8 +118,11 @@ runs:
           # Install dependencies
           echo "Installing Repo and Python"
           sudo apt update
-          sudo apt upgrade -y
-          sudo apt install -y python3 python-is-python3 git curl
+          sudo apt -o Dir::Cache="$APT_CACHE_DIR" upgrade -yq
+          sudo apt -o Dir::Cache="$APT_CACHE_DIR" install -yq  python3 python-is-python3 git curl ccache \
+            libelf-dev  build-essential flex bison libssl-dev \
+            libncurses-dev liblz4-tool zlib1g-dev \
+            libxml2-utils rsync unzip & git lfs install
           
           mkdir -p ./git-repo
           curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
@@ -99,15 +132,50 @@ runs:
           # Set CONFIG Environment Variable
           echo "CONFIG=${{ inputs.model }}" >> $GITHUB_ENV
 
-      - name: Configure Git & Install dependencies # 配置 Git & 安装依赖
+      - name: ⚙️ Set device-specific CCACHE_DIR (设置对应机型Ccache路径)
+        shell: bash
+        run: |
+          echo "CCACHE_DIR=$HOME/.ccache_${CONFIG}" >> $GITHUB_ENV
+          mkdir -p "$HOME/.ccache_${CONFIG}"
+          echo "set: $HOME/.ccache_${CONFIG}"
+
+      - name: Configure Git # 配置 Git 
         shell: bash
         run: |
           git config --global user.name "gsongX"
           git config --global user.email "gsong2014@foxmail.com"
-          sudo apt update -y
-          sudo apt-mark hold firefox
-          sudo apt upgrade -y -o Dpkg::Options::="--force-confold"
-          sudo apt install -y python3 git git-lfs curl && git lfs install
+
+      - name: 📥 Restore ccache (载入 机型：${{ env.CONFIG }}的 ccache 缓存)
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.CCACHE_DIR }}
+          key: ccache-${{ runner.os }}-${{ github.ref }}-${{ env.CONFIG }}
+          restore-keys: |
+            ccache-${{ runner.os }}-${{ env.CONFIG }}-
+            ccache-${{ runner.os }}-
+
+      - name: 📥 Init ccache (如果是第一次运行则初始化Ccache)
+        shell: bash
+        run: |
+          export CCACHE_COMPILERCHECK="%compiler% -dumpmachine; %compiler% -dumpversion"
+          export CCACHE_NOHASHDIR="true"
+          export CCACHE_HARDLINK="true"
+          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
+          export CCACHE_MAXSIZE="8G"
+
+          INIT_FLAG="$CCACHE_DIR/.ccache_initialized"
+          if command -v ccache >/dev/null 2>&1; then
+            if [ ! -f "$INIT_FLAG" ]; then
+              echo "初始化 ccache ($CCACHE_DIR)..."
+              mkdir -p "$CCACHE_DIR"
+              ccache -M "$CCACHE_MAXSIZE"
+              touch "$INIT_FLAG"
+            else
+              echo "ccache 已初始化，跳过"
+            fi
+          else
+            echo "未安装 ccache，跳过"
+          fi
 
       - name: Set Environment Variable # 设置内核环境变量
         shell: bash
@@ -271,9 +339,8 @@ runs:
               #Hunk #1 FAILED at 314.
               cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_apk_sign.c.patch" ./
               patch -p1 --forward --fuzz=3 < fix_apk_sign.c.patch
-              #Hunk #2 FAILED at 46.
-              #Hunk #14 FAILED at 915.
-              #Hunk #18 FAILED at 1009.
+              #Hunk #14 FAILED at 986.
+              #Hunk #18 FAILED at 1102.
               cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_core_hook.c.patch" ./
               patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch
               #Hunk #3 FAILED at 57.
@@ -285,6 +352,11 @@ runs:
               #Hunk #1 FAILED at 24
               cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_rules.c.patch" ./
               patch -p1 --forward --fuzz=3 < fix_rules.c.patch
+              #Hunk #3 FAILED at 38.
+              #Hunk #4 FAILED at 73.
+              #Hunk #7 FAILED at 148.
+              cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_sucompat.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_sucompat.c.patch
               ;;
             *)
               echo "Invalid version: $susfs_version"
@@ -427,6 +499,7 @@ runs:
 
           # ===== 编译优化 =====
           # 启用LTO和优化选项
+          echo 'CONFIG_LTO=y' >> "$DEFCONFIG"
           echo "CONFIG_LTO_CLANG=y" >> "$DEFCONFIG"
           echo "CONFIG_LTO_CLANG_THIN=y" >> "$DEFCONFIG"
           echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> "$DEFCONFIG"
@@ -434,42 +507,36 @@ runs:
           # echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3=y" >> "$DEFCONFIG"
 
           # Wakelock Blocker
-          echo "CONFIG_BOEFFLA_WL_BLOCKER=y" >> "$DEFCONFIG"
-          sed -i 's/CONFIG_PM_WAKELOCKS_LIMIT=0/CONFIG_PM_WAKELOCKS_LIMIT=10/' "$DEFCONFIG"
-          sed -i 's/# CONFIG_PM_WAKELOCKS_GC is not set/CONFIG_PM_WAKELOCKS_GC=y/' "$DEFCONFIG"
-          sed -i 's/placeholder/gauge;sscrpcd:2310;b0000000.qcom,cnss-peach;wired wakelock;cne_wl_;radio-data-interface;fastrpc-secure;event0;event8;event2;event3;9-0028;amd_lock;lux_aod_lock;a600000.ssusb;qcom_rx_wakelock;wlan;wlan_wow_wl;IPA_WS;wlan_ipa;wlan_pno_wl;DIAG_WS;qcom_sap_wakelock;pmo_wow_wl;898000.qcom,qup_uart;rmnet_ctl;SensorsHAL_WAKEUP;ena600000.ssusb;gesture_prox_lock;gnss_hal;prox_lock;IPA_CLIENT_APPS_LAN_CONS;IPA_CLIENT_APPS_WAN_LOW_LAT_CONS;RMNET_SHS;IPA_CLIENT_APPS_WAN_COAL_CONS;oplus_shaking_lock;8-0028;phone_prox_lock;qrtr_ws;rmnet_ipa%d;wlan_ap_assoc_lost_wl;radio-data-interface;tftp_server_wakelock;pedometer_minute_lock;wlan_roam_ho_wl;wlan_rx_wakelock;ipa_ws;cnss_daemon_wa;LocationManagerService;NlpWakelock;SensorService;AudioMix;*backup*;SyncManagerWakelock;10-0028;vdev_start;event8;eventpoll/' "$COMMON/drivers/base/power/boeffla_wl_blocker.h" || true
+          # echo "CONFIG_BOEFFLA_WL_BLOCKER=y" >> "$DEFCONFIG"
+          # sed -i 's/CONFIG_PM_WAKELOCKS_LIMIT=0/CONFIG_PM_WAKELOCKS_LIMIT=10/' "$DEFCONFIG"
+          # sed -i 's/# CONFIG_PM_WAKELOCKS_GC is not set/CONFIG_PM_WAKELOCKS_GC=y/' "$DEFCONFIG"
+          # sed -i 's/placeholder/gauge;sscrpcd:2310;b0000000.qcom,cnss-peach;wired wakelock;cne_wl_;radio-data-interface;fastrpc-secure;event0;event8;event2;event3;9-0028;amd_lock;lux_aod_lock;a600000.ssusb;qcom_rx_wakelock;wlan;wlan_wow_wl;IPA_WS;wlan_ipa;wlan_pno_wl;DIAG_WS;qcom_sap_wakelock;pmo_wow_wl;898000.qcom,qup_uart;rmnet_ctl;SensorsHAL_WAKEUP;ena600000.ssusb;gesture_prox_lock;gnss_hal;prox_lock;IPA_CLIENT_APPS_LAN_CONS;IPA_CLIENT_APPS_WAN_LOW_LAT_CONS;RMNET_SHS;IPA_CLIENT_APPS_WAN_COAL_CONS;oplus_shaking_lock;8-0028;phone_prox_lock;qrtr_ws;rmnet_ipa%d;wlan_ap_assoc_lost_wl;radio-data-interface;tftp_server_wakelock;pedometer_minute_lock;wlan_roam_ho_wl;wlan_rx_wakelock;ipa_ws;cnss_daemon_wa;LocationManagerService;NlpWakelock;SensorService;AudioMix;*backup*;SyncManagerWakelock;10-0028;vdev_start;event8;eventpoll/' "$COMMON/drivers/base/power/boeffla_wl_blocker.h" || true
           # sed -i 's/placeholder/gauge;sscrpcd:2310;b0000000.qcom,cnss-peach;wired wakelock;cne_wl_;radio-data-interface;fastrpc-secure;eventpoll;event0;event8;event2;event3;9-0028;amd_lock;lux_aod_lock;a600000.ssusb;qcom_rx_wakelock;wlan;wlan_wow_wl;NETLINK;IPA_WS;\[timerfd\];wlan_ipa;wlan_pno_wl;DIAG_WS;qcom_sap_wakelock;pmo_wow_wl;898000.qcom,qup_uart;rmnet_ctl;hal_bluetooth_lock;SensorsHAL_WAKEUP;ena600000.ssusb;gesture_prox_lock;gnss_hal;prox_lock;IPA_CLIENT_APPS_LAN_CONS;IPA_CLIENT_APPS_WAN_LOW_LAT_CONS;RMNET_SHS;IPA_CLIENT_APPS_WAN_COAL_CONS;oplus_shaking_lock;8-0028;phone_prox_lock;qrtr_ws;rmnet_ipa%d;wlan_ap_assoc_lost_wl;radio-data-interface;tftp_server_wakelock;pedometer_minute_lock;wlan_roam_ho_wl;10-0028;vdev_start;event8;eventpoll/' "$COMMON/drivers/base/power/boeffla_wl_blocker.h" || true
 
           # Optimization
-          echo "CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y" >> "$DEFCONFIG"
-          echo "CONFIG_DYNAMIC_FTRACE_WITH_CALL_OPS=y" >> "$DEFCONFIG"
-          echo "CONFIG_SCHED_CLUSTER=y" >> "$DEFCONFIG"
-
-          # Polly
-          #echo "CONFIG_POLLY_CLANG=y" >> "$DEFCONFIG"
-          echo "CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y" >> "$DEFCONFIG"
+          # echo "CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y" >> "$DEFCONFIG"
+          # echo "CONFIG_DYNAMIC_FTRACE_WITH_CALL_OPS=y" >> "$DEFCONFIG"
 
           # LRNG
-          echo "CONFIG_LRNG=y" >> "$DEFCONFIG"
-          echo "CONFIG_RANDOM_DEFAULT_IMPL=n" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_IRQ=n" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_SCHED=n" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_CPU=y" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_JENT=n" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_CONTINUOUS_COMPRESSION_ENABLED=y" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_DRNG_ATOMIC=y" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_SELFTEST=n" >> "$DEFCONFIG"
-          echo "CONFIG_LRNG_RANDOM_IF=y" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG=y" >> "$DEFCONFIG"
+          # echo "CONFIG_RANDOM_DEFAULT_IMPL=n" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_IRQ=n" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_SCHED=n" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_CPU=y" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_JENT=n" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_CONTINUOUS_COMPRESSION_ENABLED=y" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_DRNG_ATOMIC=y" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_SELFTEST=n" >> "$DEFCONFIG"
+          # echo "CONFIG_LRNG_RANDOM_IF=y" >> "$DEFCONFIG"
           
           # Filesystem Features
-          echo "CONFIG_TMPFS_XATTR=y" >> "$DEFCONFIG"
-          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$DEFCONFIG"
+          # echo "CONFIG_TMPFS_XATTR=y" >> "$DEFCONFIG"  #若不使用 SELinux 细粒度控制，会增加内存操作开销
+          # echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$DEFCONFIG"
 
 
           # Remove unnecessary defconfig entries
           sed -i "s/CONFIG_PRINTK_TIME=y/CONFIG_PRINTK_TIME=n/" "$DEFCONFIG"
           sed -i "s/CONFIG_PRINTK_CALLER=y/CONFIG_PRINTK_CALLER=n/" "$DEFCONFIG"
-          echo "CONFIG_TCP_CONG_CUBIC=n" >> "$DEFCONFIG"
           echo "CONFIG_MQ_IOSCHED_KYBER=n" >> "$DEFCONFIG"
 
           # ===== F2FS优化 =====
@@ -507,9 +574,8 @@ runs:
         run: |          
           cd "$CONFIG/kernel_platform/common"
           if [ "${{ inputs.kernel_version }}" = "6.6" ]; then
-              wget https://github.com/gsongX/OnePlus_KernelSU_SUSFS/raw/dev/patchs/6.6/blacklist_module.patch
               if [ -z "$(grep "blocked_modules" kernel/module/main.c)" ]; then
-                patch -p1 -F 3 < blacklist_module.patch || true
+                patch -p1 -F 3 < ../../../patchs/6.6/blacklist_module.patch || true
               fi
           fi
           # Remove check_defconfig
@@ -519,14 +585,13 @@ runs:
       - name: Fix upstream bugs
         shell: bash
         run: |
-          cd "$CONFIG/kernel_platform/common"      
+          cd "$CONFIG/kernel_platform/common"
+          # "unlock_cpufreq.patch" \ 
           if [ "${{ inputs.kernel_version }}" = "6.6" ]; then
               for i in "fix_screen_off_crash.patch" \
                 "fix_screen_flicker.patch" \
-                "unlock_cpufreq.patch" \
                 "fix_usb_network_share.patch"; do
-                 wget https://github.com/gsongX/OnePlus_KernelSU_SUSFS/raw/dev/patchs/6.6/$i
-                 patch -p1 -F 3 < $i || true
+                 patch -p1 -F 3 < ../../../patchs/6.6/$i || true
               done
           fi
           
@@ -556,9 +621,6 @@ runs:
           sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"
 
           # Set LTO
-          echo 'CONFIG_LTO=y' >> "$DEFCONFIG"
-          echo 'CONFIG_LTO_CLANG_THIN=y' >> "$DEFCONFIG"
-          echo 'CONFIG_LTO_CLANG_THIN=y' >>"$DEFCONFIG"
           sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "$DEFCONFIG"
           sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
           sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
@@ -608,7 +670,8 @@ runs:
             ./kernel_platform/oplus/bazel/oplus_modules_variant.sh ${{ inputs.soc }} "$BUILD_TYPE" ""
             ./kernel_platform/build_with_bazel.py -t ${{ inputs.soc }} $BUILD_TYPE "${BAZEL_ARGS[@]}" -o "$(pwd)/out"
           else
-            LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} "$BUILD_TYPE"
+            LTO=thin SYSTEM_DLKM_RE_SIGN=0 BUILD_SYSTEM_DLKM=0 KMI_SYMBOL_LIST_STRICT_MODE=0 \
+             ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} "$BUILD_TYPE"
           fi
 
       - name: Create ZIP Files for Different Formats
