Update Build SukiSU Ultra OnePlus.yml

diff --git a/.github/workflows/Build SukiSU Ultra OnePlus.yml b/.github/workflows/Build SukiSU Ultra OnePlus.yml
--- a/.github/workflows/Build SukiSU Ultra OnePlus.yml
+++ b/.github/workflows/Build SukiSU Ultra OnePlus.yml
@@ -104,32 +104,32 @@ jobs:
           
           # Define valid combinations with base model only (no _v/_u/_t..) 仅保留机型信息前缀,去除可能存在的最后一个后缀(_v/_u/_t..)
           declare -A VALID_COMBINATIONS=(
-            ["oneplus_nord_ce4_lite_5g"]="sm6375 blair android14 6.1"
-            ["oneplus_nord_ce4"]="sm7550 crow android14 5.15"
-            ["oneplus_nord_4"]="sm7675 pineapple android14 6.1"
-            ["oneplus_ace_3v"]="sm7675 pineapple android14 6.1"
-            ["oneplus_10_pro"]="sm8450 waipio android12 5.10"
-            ["oneplus_10t"]="sm8475 waipio android12 5.10"
-            ["oneplus_11r"]="sm8475 waipio android12 5.10"
-            ["oneplus_ace2"]="sm8475 waipio android12 5.10"
-            ["oneplus_ace_pro"]="sm8475 waipio android12 5.10"
-            ["oneplus_11"]="sm8550 kalama android13 5.15"
-            ["oneplus_12r"]="sm8550 kalama android13 5.15"
-            ["oneplus_ace2_pro"]="sm8550 kalama android13 5.15"
-            ["oneplus_ace3"]="sm8550 kalama android13 5.15"
-            ["oneplus_open"]="sm8550 kalama android13 5.15"
-            ["oneplus12"]="sm8650 pineapple android14 6.1"
-            ["oneplus_13r"]="sm8650 pineapple android14 6.1"
-            ["oneplus_ace3_pro"]="sm8650 pineapple android14 6.1"
-            ["oneplus_ace5"]="sm8650 pineapple android14 6.1"
-            ["oneplus_pad_pro"]="sm8650 pineapple android14 6.1"
-            ["oneplus_pad2"]="sm8650 pineapple android14 6.1"
-            ["oneplus_ace5_pro"]="sm8750 sun android15 6.6"
-            ["oneplus_13"]="sm8750 sun android15 6.6"
-            ["oneplus_13t"]="sm8750 sun android15 6.6"
-            ["oneplus_13s"]="sm8750 sun android15 6.6"
-            ["oneplus_pad_2_pro"]="sm8750 sun android15 6.6"
-            ["oneplus_pad_3"]="sm8750 sun android15 6.6"
+            ["oneplus_nord_ce4_lite_5g"]="OP-NORD-CE4-LITE sm6375 blair android14 6.1"
+            ["oneplus_nord_ce4"]="OP-NORD-CE4 sm7550 crow android14 5.15"
+            ["oneplus_nord_4"]="OP-NORD-4 sm7675 pineapple android14 6.1"
+            ["oneplus_ace_3v"]="OP-ACE-3V sm7675 pineapple android14 6.1"
+            ["oneplus_10_pro"]="OP10pro sm8450 waipio android12 5.10"
+            ["oneplus_10t"]="OP10t sm8475 waipio android12 5.10"
+            ["oneplus_11r"]="OP11r sm8475 waipio android12 5.10"
+            ["oneplus_ace2"]="OP-ACE-2 sm8475 waipio android12 5.10"
+            ["oneplus_ace_pro"]="OP-ACE-PRO sm8475 waipio android12 5.10"
+            ["oneplus_11"]="OP11 sm8550 kalama android13 5.15"
+            ["oneplus_12r"]="OP12r sm8550 kalama android13 5.15"
+            ["oneplus_ace2_pro"]="OP-ACE-2-PRO sm8550 kalama android13 5.15"
+            ["oneplus_ace3"]="OP-ACE-3 sm8550 kalama android13 5.15"
+            ["oneplus_open"]="OP-OPEN sm8550 kalama android13 5.15"
+            ["oneplus12_v"]="OP12 sm8650 pineapple android14 6.1"
+            ["oneplus_13r"]="OP-13R sm8650 pineapple android14 6.1"
+            ["oneplus_ace3_pro"]="OP-ACE-3-PRO sm8650 pineapple android14 6.1"
+            ["oneplus_ace5"]="OPAce5 sm8650 pineapple android14 6.1"
+            ["oneplus_pad_pro"]="OP-PAD-PRO sm8650 pineapple android14 6.1"
+            ["oneplus_pad2"]="OP-PAD-2 sm8650 pineapple android14 6.1"
+            ["oneplus_ace5_pro"]="OPAce5Pro sm8750 sun android15 6.6"
+            ["oneplus_13"]="OP13 sm8750 sun android15 6.6"
+            ["oneplus_13t"]="OP13T sm8750 sun android15 6.6"
+            ["oneplus_13s"]="OP13S sm8750 sun android15 6.6"
+            ["oneplus_pad_2_pro"]="OP-PAD-2-PRO sm8750 sun android15 6.6"
+            ["oneplus_pad_3"]="OP-PAD-3 sm8750 sun android15 6.6"
           )
 
           get_combination() {
@@ -157,9 +157,10 @@ jobs:
             exit 1
           }
 
-          read CPU CPUD ANDROID_VERSION KERNEL_VERSION <<< "$COMBINATION"
+          read CONFIG CPU CPUD ANDROID_VERSION KERNEL_VERSION <<< "$COMBINATION"
 
-          echo "✅ Valid combination: FILE=$FILE, CPU=$CPU, CPUD=$CPUD, ANDROID_VERSION=$ANDROID_VERSION, KERNEL_VERSION=$KERNEL_VERSION"
+          echo "✅ Valid combination: FILE=$FILE, CONFIG=$CONFIG, CPU=$CPU, CPUD=$CPUD, ANDROID_VERSION=$ANDROID_VERSION, KERNEL_VERSION=$KERNEL_VERSION"
+          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
           echo "CPU=$CPU" >> $GITHUB_ENV
           echo "CPUD=$CPUD" >> $GITHUB_ENV
           echo "ANDROID_VERSION=$ANDROID_VERSION" >> $GITHUB_ENV
@@ -172,11 +173,59 @@ jobs:
             echo "BUILD_METHOD=gki" >> $GITHUB_ENV
           fi
 
+      - name: Check Disk Space
+        run: df -h
+
+      - name: Maximize Build Space
+        uses: AdityaGarg8/remove-unwanted-software@v5
+        with:
+          remove-dotnet: 'true'          # Frees ~2 GB
+          remove-android: 'true'         # Frees ~9 GB
+          remove-haskell: 'true'         # Frees ~5.2 GB
+          remove-codeql: 'true'          # Frees ~5.4 GB
+          remove-docker-images: 'true'   # Frees ~3.2 GB
+          remove-large-packages: 'true'  # Frees ~3.1 GB
+          remove-swapfile: 'true'        # Frees ~4 GB
+          remove-cached-tools: 'false'   # Avoid unless confirmed safe
+          verbose: 'false'                # Enable detailed logging
+
+      - name: APT remove unneed
+        shell: bash
+        run: |
+          export DEBIAN_FRONTEND=noninteractive
+          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+          
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+          sudo docker image prune --all --force
+          echo "some directories deleted"
+          
+          # Remove large unwanted packages
+          sudo apt-get purge -y \
+            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+          
+          # Regex-based purges (for bulk families like mysql, php, dotnet)
+          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+          
+          # Clean up
+          sudo apt-get autoremove -y
+          sudo apt-get autoclean -y
+          echo "some packages purged"
+          
+          df -h
+
       - name: Set Environment Variable # 设置内核环境变量
         shell: bash
         run: |
           # PLATFORM_DIR=/home/runner/work/OnePlus_KernelSU_SUSFS/OnePlus_KernelSU_SUSFS/kernel_platform
-          WORKSPACE_DIR="$GITHUB_WORKSPACE"
+          WORKSPACE_DIR="$GITHUB_WORKSPACE/$CONFIG"
           PLATFORM_DIR="$WORKSPACE_DIR/kernel_platform"
           COMMON_DIR="$PLATFORM_DIR/common"
           DEFCONFIG="$COMMON_DIR/arch/arm64/configs/gki_defconfig"
@@ -189,6 +238,7 @@ jobs:
           echo "DEFCONFIG=$DEFCONFIG" >> $GITHUB_ENV
           echo "MSMCONFIG=$MSMCONFIG" >> $GITHUB_ENV
 
+          echo "REPO_MANIFEST=${{ github.event.inputs.REPO_MANIFEST }}" >> $GITHUB_ENV
           echo "KEEP_ORIGINAL=${{ github.event.inputs.KEEP_ORIGINAL_SETTINGS }}" >> $GITHUB_ENV
           echo "CUSTOM_SUFFIX=${{ github.event.inputs.SUFFIX }}" >> $GITHUB_ENV
           echo "CUSTOM_TIME=${{ github.event.inputs.BUILD_TIME }}" >> $GITHUB_ENV
@@ -236,28 +286,6 @@ jobs:
                 ;;
             esac
           fi
-
-      - name: Check Disk Space
-        run: df -h
-
-      - name: Maximize Build Space
-        uses: AdityaGarg8/remove-unwanted-software@v5
-        with:
-          remove-dotnet: 'true'          # Frees ~2 GB
-          remove-android: 'true'         # Frees ~9 GB
-          remove-haskell: 'true'         # Frees ~5.2 GB
-          remove-codeql: 'true'          # Frees ~5.4 GB
-          remove-docker-images: 'true'   # Frees ~3.2 GB
-          remove-large-packages: 'true'  # Frees ~3.1 GB
-          remove-swapfile: 'true'        # Frees ~4 GB
-          remove-cached-tools: 'false'   # Avoid unless confirmed safe
-          verbose: 'false'                # Enable detailed logging
-
-      - name: Maximize Build Space
-        uses: easimon/maximize-build-space@master
-        with:
-          root-reserve-mb: 8192
-          temp-reserve-mb: 2048
 
       - name: Create and Enable 3G Swap
         run: |
@@ -321,17 +349,16 @@ jobs:
           APT_CACHE_DIR="$HOME/apt-cache"
           mkdir -p "$APT_CACHE_DIR/lists/partial"
           sudo apt -o Dir::Cache="$APT_CACHE_DIR" update -qq
-          sudo DEBIAN_FRONTEND=noninteractive apt -o Dir::Cache="$APT_CACHE_DIR" install -yq --no-install-recommends \
-            python3 git curl ccache libelf-dev \
-            build-essential flex bison libssl-dev \
+          sudo apt -o Dir::Cache="$APT_CACHE_DIR" install -yq python3 \
+            python-is-python3 git curl ccache libelf-dev  build-essential flex bison libssl-dev \
             libncurses-dev liblz4-tool zlib1g-dev \
-            libxml2-utils rsync unzip
+            libxml2-utils rsync unzip & git lfs install
 
       - name: Restore Ccache
         uses: actions/cache@v3
         with:
           path: ${{ env.CCACHE_DIR }}
-          key: ccache-${{ runner.os }}-${{ github.ref_name }}-${REPO_MANIFEST}-${{ env.BUILD_METHOD }}-${{ github.event.inputs.FAST_BUILD == 'true' && 'alpha' || 'beta' }}-15
+          key: ccache-${{ runner.os }}-${{ github.ref_name }}-${{ env.CONFIG }}-${{ env.BUILD_METHOD }}-${{ github.event.inputs.FAST_BUILD == 'true' && 'alpha' || 'beta' }}-15
 
       - name: Initialize Ccache
         run: |
@@ -359,9 +386,11 @@ jobs:
 
       - name: Initialize Repo and Sync
         run: |
+          mkdir -p "$CONFIG"
           cd $WORKSPACE
           repo init -u https://github.com/gsongX/kernel_manifest.git -b refs/heads/oneplus/${{ env.CPU }} -m ${REPO_MANIFEST}.xml --depth=1
-          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
+          repo --version
+          repo --trace sync -c --no-clone-bundle --no-tags --optimized-fetch -j$(nproc --all) --fail-fast || { echo "repo sync 失败"; exit 1; }
           if [ -e $PLATFORM/common/BUILD.bazel ]; then
             sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' $PLATFORM/common/BUILD.bazel
           fi
@@ -419,7 +448,7 @@ jobs:
 
       # 自定义内核后缀
       - name: Custom Kernel Suffix if set
-        if: ${{ github.event.inputs.SUFFIX != '' }} && [ -n "$DEFAULT_SUFFIX" ]
+        if: ${{ github.event.inputs.SUFFIX != '' && env.DEFAULT_SUFFIX == '' }}
         run: |
           cd $WORKSPACE
           SUFFIX="${{ github.event.inputs.SUFFIX }}"
@@ -469,7 +498,7 @@ jobs:
 
       # 伪官方格式的随机后缀（仅在 SUFFIX 未设置时生效）*
       - name: Custom Kernel Random Suffix if empty
-        if: ${{ github.event.inputs.SUFFIX == '' }} && [ -n "$DEFAULT_SUFFIX" ]
+        if: ${{ github.event.inputs.SUFFIX == '' && env.DEFAULT_SUFFIX == '' }} 
         run: |
           cd $WORKSPACE
           ANDROID_VERSION="${{ env.ANDROID_VERSION }}"
@@ -597,6 +626,8 @@ jobs:
           patch -p1 -F 3 < syscall_hooks.patch
           echo "vfs_patch完成"
 
+          cd $WORKSPACE
+
           if [ "${{ github.event.inputs.ZRAM }}" = "true" ]; then
             echo "正在拉取zram补丁"
             cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* $PLATFORM/common/include/linux/
@@ -618,7 +649,7 @@ jobs:
           KERNEL_VERSION="${{ env.KERNEL_VERSION }}"
           TRUSTY_EXISTS="false"
           if [[ "$KERNEL_VERSION" == "6.6" ]]; then
-            if grep -qr 'common-modules/trusty' "$WORKSPACE/.repo/manifests_fallback/${REPO_MANIFEST}.xml"; then
+            if grep -qr 'common-modules/trusty' "$GITHUB_WORKSPACE/.repo/manifests_fallback/${REPO_MANIFEST}.xml"; then
               TRUSTY_EXISTS="true"
             fi
             echo "trusty_exists=$TRUSTY_EXISTS" >> $GITHUB_OUTPUT
@@ -742,7 +773,7 @@ jobs:
 
       # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
       - name: Custom BUILD_TIME
-        if: ${{ github.event.inputs.BUILD_TIME != '' && !contains('Ff', github.event.inputs.BUILD_TIME) }} && [ -n "$KERNEL_TIME" ]
+        if: ${{ github.event.inputs.BUILD_TIME != '' && !contains('Ff', github.event.inputs.BUILD_TIME) && env.KERNEL_TIME == '' }}
         shell: bash
         run: |
           DATESTR="${{ github.event.inputs.BUILD_TIME }}"
@@ -796,17 +827,35 @@ jobs:
           export PATH="$PLATFORM/$CLANG_DIR/clang/host/linux-x86/$CLANG_PATH/bin:$PATH"
           export PATH="/usr/lib/ccache:$PATH"
           export CC="ccache clang"
-          sudo apt install -y libelf-dev ccache
           cd $WORKSPACE/kernel_platform/common
-          MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
-            RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
-            PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
-            LD=ld.lld HOSTLD=ld.lld KCFLAGS+=-Wno-error"
+
+          export CCACHE_COMPILERCHECK="%compiler% -dumpmachine; %compiler% -dumpversion"
+          export CCACHE_NOHASHDIR="true"
+          export CCACHE_HARDLINK="true"
+          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
+          export CCACHE_MAXSIZE="8G"
+          
+          if [[ "$KBUILD_BUILD_TIMESTAMP" == "" ]]; then
+            export KBUILD_BUILD_TIMESTAMP="${KERNEL_TIME}"
+            echo "KBUILD_BUILD_TIMESTAMP=${KERNEL_TIME}" >> "$GITHUB_ENV"
+          fi
+
+          MAKE_ARGS=(
+            "LLVM=1"
+            "ARCH=arm64"
+            "CC=ccache clang"
+            "CROSS_COMPILE=aarch64-linux-gnu-"
+            "RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc"
+            "PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole"
+            "LD=ld.lld"
+            "HOSTLD=ld.lld"
+            "KCFLAGS+=-Wno-error"
+          )
           if [[ "$USE_LLVM_IAS" == "true" ]]; then
             MAKE_ARGS="LLVM_IAS=1 $MAKE_ARGS"
           fi
-          make -j$(nproc --all) O=out $MAKE_ARGS gki_defconfig
-          make -j$(nproc --all) O=out $MAKE_ARGS
+          make -j$(nproc --all) O=out "${MAKE_ARGS[@]}" gki_defconfig
+          make -j$(nproc --all) O=out "${MAKE_ARGS[@]}"
           ccache -s
 
       - name: Fallback to Build Kernel
@@ -935,7 +984,7 @@ jobs:
         run: |
           cpu="${{ env.CPU }}"
           xml=".repo/manifests_fallback/${REPO_MANIFEST}.xml"
-          cd $WORKSPACE
+          cd $GITHUB_WORKSPACE
           file_base=$(echo "$REPO_MANIFEST" | sed -E 's/_[a-z]$//')
           revision_full=$(grep -oP '<project[^>]*name="android_kernel[^"]*"[^>]*revision="\K[^"]+' "$xml" | head -n1 || true)
           if [ -n "$revision_full" ]; then
